{
    "response": {
        "stepId": "FactorStep(product=2)",
        "error": "Runtime error:\nTraceback (most recent call last):\n  File '/Users/davw/projects/trun-core/trun/worker.py', line 164, in _run_step\n    step.run()\n  File '/Users/davw/projects/trun-core/test/scheduler_visualisation_test.py', line 62, in run\n    raise Exception('Error Message')\nException: Error Message\n"
    }
}